//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datally.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datally.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup\.
        /// </summary>
        internal static string BackupFolder {
            get {
                return ResourceManager.GetString("BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close_white_18 {
            get {
                object obj = ResourceManager.GetObject("Close_white_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ???.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copyright_white_18 {
            get {
                object obj = ResourceManager.GetObject("Copyright_white_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dark_Delete_18 {
            get {
                object obj = ResourceManager.GetObject("Dark_Delete_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataGo {
            get {
                object obj = ResourceManager.GetObject("DataGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DB1 {
            get {
                return ResourceManager.GetString("DB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string DB2 {
            get {
                return ResourceManager.GetString("DB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWord.
        /// </summary>
        internal static string DB3 {
            get {
                return ResourceManager.GetString("DB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string DB4 {
            get {
                return ResourceManager.GetString("DB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleID.
        /// </summary>
        internal static string DB5 {
            get {
                return ResourceManager.GetString("DB5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_Status.
        /// </summary>
        internal static string DB6 {
            get {
                return ResourceManager.GetString("DB6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\DataBase\.
        /// </summary>
        internal static string DDB {
            get {
                return ResourceManager.GetString("DDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\Medical Report\.
        /// </summary>
        internal static string DMR {
            get {
                return ResourceManager.GetString("DMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\P_Report.
        /// </summary>
        internal static string DP_Report {
            get {
                return ResourceManager.GetString("DP_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\Templete.
        /// </summary>
        internal static string DTemplete {
            get {
                return ResourceManager.GetString("DTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is Some Problem.
        /// </summary>
        internal static string E11 {
            get {
                return ResourceManager.GetString("E11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelease Enter Service and Doctor Name.
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Your Data and Try Again.
        /// </summary>
        internal static string E5 {
            get {
                return ResourceManager.GetString("E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call IT Administrator.
        /// </summary>
        internal static string E6 {
            get {
                return ResourceManager.GetString("E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password is not correct.
        /// </summary>
        internal static string E7 {
            get {
                return ResourceManager.GetString("E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string E8 {
            get {
                return ResourceManager.GetString("E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Really Want to Closing The Program?.
        /// </summary>
        internal static string E9 {
            get {
                return ResourceManager.GetString("E9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exist.
        /// </summary>
        internal static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_account_circle_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_account_circle_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_add_circle_outline_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_add_circle_outline_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_cancel_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_cancel_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_clear_white_24dp {
            get {
                object obj = ResourceManager.GetObject("ic_clear_white_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_create_new_folder_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_create_new_folder_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_edit_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_edit_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_exit_to_app_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_exit_to_app_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_folder_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_folder_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_input_white_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_input_white_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_power_settings_new_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_power_settings_new_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_print_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_print_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_remove_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_remove_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_save_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_save_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_send_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_send_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_youtube_searched_for_white_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_youtube_searched_for_white_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Light_Arrow_Left_36 {
            get {
                object obj = ResourceManager.GetObject("Light_Arrow_Left_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Light_Arrow_Right_36 {
            get {
                object obj = ResourceManager.GetObject("Light_Arrow_Right_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Light_Info_Outline_36 {
            get {
                object obj = ResourceManager.GetObject("Light_Info_Outline_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry You Can&apos;t Make Templete, Call IT Administrator.
        /// </summary>
        internal static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\Medical Report\Backup.
        /// </summary>
        internal static string MRpath3 {
            get {
                return ResourceManager.GetString("MRpath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Exist.
        /// </summary>
        internal static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap outline_logout_white_20 {
            get {
                object obj = ResourceManager.GetObject("outline_logout_white_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.StartupPath\.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\DataBase\Radiologix.accdb.
        /// </summary>
        internal static string Path2 {
            get {
                return ResourceManager.GetString("Path2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\Backup\.
        /// </summary>
        internal static string PathBackup {
            get {
                return ResourceManager.GetString("PathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\P_Report\.
        /// </summary>
        internal static string PathP_ReportBackup {
            get {
                return ResourceManager.GetString("PathP_ReportBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radiologix {
            get {
                object obj = ResourceManager.GetObject("Radiologix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radiologix_250 {
            get {
                object obj = ResourceManager.GetObject("Radiologix_250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radiologix_App {
            get {
                object obj = ResourceManager.GetObject("Radiologix App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RADIOLOGIX_Trans {
            get {
                object obj = ResourceManager.GetObject("RADIOLOGIX_Trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reception_White_32 {
            get {
                object obj = ResourceManager.GetObject("Reception_White_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\r\n&quot;.
        /// </summary>
        internal static string S0 {
            get {
                return ResourceManager.GetString("S0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string S1 {
            get {
                return ResourceManager.GetString("S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodBye.
        /// </summary>
        internal static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|.
        /// </summary>
        internal static string SVR {
            get {
                return ResourceManager.GetString("SVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\SVR1\d\Datally\Backup\.
        /// </summary>
        internal static string SVRBackup {
            get {
                return ResourceManager.GetString("SVRBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.ACE.OLEDB.16.0;Data Source=|DataDirectory|\\DataBase\\Radiologix.accdb;Jet OLEDB:Database Password=Radiologix@2024$.
        /// </summary>
        internal static string SVRDB {
            get {
                return ResourceManager.GetString("SVRDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\SVR1\d\Datally\Medical Report\.
        /// </summary>
        internal static string SVRMR {
            get {
                return ResourceManager.GetString("SVRMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\SVR1\d\Datally\P_Report\.
        /// </summary>
        internal static string SVRP_Report {
            get {
                return ResourceManager.GetString("SVRP_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase\Radiologix.accdb.
        /// </summary>
        internal static string SVRPath {
            get {
                return ResourceManager.GetString("SVRPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |DataDirectory|\Templete\.
        /// </summary>
        internal static string SVRTemplete {
            get {
                return ResourceManager.GetString("SVRTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Template_White_32 {
            get {
                object obj = ResourceManager.GetObject("Template_White_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Test\.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
